name: Test Branch on Flix Release

on:
  workflow_call:
    inputs:
      os:
        default: "ubuntu-latest"
        required: false
        type: string
    secrets: inherit

jobs:
  test-on-flix-nightly:
    runs-on: ${{ inputs.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2.5.0
        with:
          java-version: 21
          distribution: zulu
      - uses: SebRollen/toml-action@v1.0.2
        id: read_toml
        with:
          file: 'flix.toml'
          field: 'package.flix'
      - run: |
          # download Flix JAR
          curl -L https://github.com/flix/flix/releases/download/v${{steps.read_toml.outputs.value}}/flix.jar > flix.jar

          # run tests
          java -jar flix.jar test --github-key ${{ github.token }}