name: Test Branch on Flix Nightly

on:
  workflow_call:
    inputs:
      os:
        default: "ubuntu-latest"
        required: false
        type: string
    secrets: inherit

jobs:
  test-on-flix-nightly:
    runs-on: ${{ inputs.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2.5.0
        with:
          java-version: 21
          distribution: zulu
      - run: |
          # download the latest nightly Flix JAR
          url="https://flix.dev/nightly/flix-latest.jar"
          curl -L -f "$url" > flix.jar

          # run tests
          java -jar flix.jar test --github-key ${{ github.token }}